services:
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: synapse-server
    env_file:
      - dev.env
    volumes:
      - ./data:/data
    configs:
      - source: homeserver_config
        target: /configuration/homeserver.yaml      
      - source: log_config
        target: /configuration/development.host.log.config
    secrets:
      - source: signing_key
        target: /configuration/development.host.signing.key
    entrypoint: ./bin/bash -c
    command:
      - "chown -R $UID:$GID /data && python ./start.py"
    ports:
      - "$SYNAPSE_HOST_PORT:$SYNAPSE_CONTAINER_PORT"

configs:
  # local path
  homeserver_config:
    file: ./configuration/homeserver.yaml 
  log_config:
    file: ./configuration/development.host.log.config
secrets:
  signing_key:
    file: ./secrets/development.host.signing.key
    